services:
   sqlDatabase:
      container_name: sql_server_container
      image: mcr.microsoft.com/mssql/server:2022-latest
      hostname: mssql
      environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "MyStrongS1rootP@ssword"
        MSSQL_MEMORY_LIMIT_MB: "8144"
        MSSQL_PID: "Developer"
        MSSQL_TRUST_SERVER_CERTIFICATE: "True"
      volumes:
        - sqldata:/var/opt/mssql
      deploy:
        resources:
           limits:
            memory: 15g
            cpus: "2"
      ports:
        - "1433:1433"    
      networks:
       - sql_network

   webapi:
    image: queens-puzzle
    container_name: queenspuzzle_api_container
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
        - ConnectionStrings__DefaultConnection=Server=sql_server_container,1433;Database=Reservations;User Id=sa;Password=MyStrongS1rootP@ssword;TrustServerCertificate=true;
    restart: on-failure
    depends_on:
       sqlDatabase:
        condition: service_started
    networks:
       - sql_network      

volumes:
    sqldata:

networks:
  sql_network: